# Generated by Django 3.1.1 on 2020-10-08 16:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=75, verbose_name='Customer Name')),
                ('customer_phone', models.CharField(blank=True, help_text='No dashes, parentheses, or country code.', max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^\\d{10}$')], verbose_name='Customer Phone')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Customer Email')),
                ('vehicle', models.CharField(blank=True, help_text="What's being repaired?", max_length=250)),
                ('status', models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('C', 'Complete')], default='NS', max_length=2)),
                ('notes', models.CharField(blank=True, help_text='Enter any repair notes here.', max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date/Time Created')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='250 characters max.', max_length=250)),
                ('quantity', models.PositiveIntegerField(help_text='This is the number of parts currently in stock (but not allocated to any jobs).')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='This can be overridden when adding a part to a job.', max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Price ($)')),
                ('ignore', models.BooleanField(blank=True, default=False, help_text='Check this if you want this part to be exempted from the zero-quantity notification.', verbose_name='Ignore Empty Stock?')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Service Price ($)')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='How many instances of this part do you want to apply to this job?')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Price ($)')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.job')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part')),
            ],
        ),
    ]
