# Generated by Django 3.1.1 on 2021-01-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210105_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='ignore',
        ),
        migrations.AddField(
            model_name='part',
            name='archived',
            field=models.BooleanField(blank=True, default=False, help_text='Check this to ignore any zero-quantities of this part, and to disable any further attachments to jobs (it will not affect jobs with the part already attached).', verbose_name='Archive?'),
        ),
        migrations.AlterField(
            model_name='jobpart',
            name='tax',
            field=models.BooleanField(blank=True, default=True, help_text='Check this to charge tax for all quantities of this part (for this job).', verbose_name='Tax?'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tax',
            field=models.BooleanField(blank=True, default=False, help_text='Check this to charge tax on this service.', verbose_name='Tax?'),
        ),
    ]
