# Generated by Django 3.1.1 on 2021-01-22 22:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210121_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPart_SingleUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='250 characters max.', max_length=250)),
                ('quantity', models.PositiveIntegerField(help_text='How many instances of this part do you want to apply to this job?')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Price ($)')),
                ('tax', models.BooleanField(blank=True, default=True, help_text='Check this to charge tax for all quantities of this part (for this job).', verbose_name='Tax?')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.job')),
            ],
        ),
    ]
