# Generated by Django 3.1.1 on 2021-05-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210526_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='notes',
            field=models.CharField(blank=True, help_text='Enter any repair notes here (2500 characters max).', max_length=2500),
        ),
    ]
