version: '3.9'

secrets:
  tnr_django_secret:
    external: true
volumes:
  db:
services:
  webapp:
    image: tnr-inventory:1.1.0
    ports:
      - "8113:5000"
    volumes:
      - db:/db
      - /backups/tnr-inventory:/backups
    environment:
      DEPLOYMENT_ENV: production
      TNR_DJANGO_SECRET_FILE: /run/secrets/tnr_django_secret
      TZ: America/Kentucky/Louisville
    secrets:
      - tnr_django_secret
